# This is a SecretProviderClass example using aad-pod-identity to access the key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-podid
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"               # Set to true for using aad-pod-identity to access your key vault
    useVMManagedIdentity: "true"                                      # Set to true for using managed identity
    userAssignedIdentityID: "d8a0effb-3405-426c-8f4f-bada40b8fe3a"   # Set the clientID of the user-assigned managed identity to use
    keyvaultName: "kvforaks011"       # Set to the name of your key vault
    cloudName: ""                        # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: database-password
          objectType: secret             # object types: secret, key, or cert
          objectVersion: ""              # [OPTIONAL] object versions, default to latest if empty
        # - |
        #   objectName: key1
        #   objectType: key
        #   objectVersion: ""
    tenantId: "72f988bf-86f1-41af-91ab-2d7cd011db47"               # The tenant ID of the key vault